//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace florista.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_product
    {
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_image { get; set; }
        public string product_description { get; set; }
        public int product_price { get; set; }
        public Nullable<int> product_fk_category { get; set; }
        public Nullable<int> product_fk_admin { get; set; }
    
        public virtual tbl_admin tbl_admin { get; set; }
        public virtual tbl_category tbl_category { get; set; }
    }
}
